//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotKeyEnabled {
            get {
                return ((bool)(this["HotKeyEnabled"]));
            }
            set {
                this["HotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OcrHotKeyEnabled {
            get {
                return ((bool)(this["OcrHotKeyEnabled"]));
            }
            set {
                this["OcrHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureHotKeyEnabled {
            get {
                return ((bool)(this["CaptureHotKeyEnabled"]));
            }
            set {
                this["CaptureHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GifHotKeyEnabled {
            get {
                return ((bool)(this["GifHotKeyEnabled"]));
            }
            set {
                this["GifHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoHotKeyEnabled {
            get {
                return ((bool)(this["VideoHotKeyEnabled"]));
            }
            set {
                this["VideoHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPickHotKeyEnabled {
            get {
                return ((bool)(this["TextPickHotKeyEnabled"]));
            }
            set {
                this["TextPickHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColorPickHotKeyEnabled {
            get {
                return ((bool)(this["ColorPickHotKeyEnabled"]));
            }
            set {
                this["ColorPickHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AotHotKeyEnabled {
            get {
                return ((bool)(this["AotHotKeyEnabled"]));
            }
            set {
                this["AotHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NoteHotKeyEnabled {
            get {
                return ((bool)(this["NoteHotKeyEnabled"]));
            }
            set {
                this["NoteHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImageEditorHotKeyEnabled {
            get {
                return ((bool)(this["ImageEditorHotKeyEnabled"]));
            }
            set {
                this["ImageEditorHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DateHotKeyEnabled {
            get {
                return ((bool)(this["DateHotKeyEnabled"]));
            }
            set {
                this["DateHotKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LongDateHotKeyEnabled {
            get {
                return ((bool)(this["LongDateHotKeyEnabled"]));
            }
            set {
                this["LongDateHotKeyEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TypeMethod {
            get {
                return ((int)(this["TypeMethod"]));
            }
            set {
                this["TypeMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunElevated {
            get {
                return ((bool)(this["RunElevated"]));
            }
            set {
                this["RunElevated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int KeyDelayMS {
            get {
                return ((int)(this["KeyDelayMS"]));
            }
            set {
                this["KeyDelayMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public string HotKey {
            get {
                return ((string)(this["HotKey"]));
            }
            set {
                this["HotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int HotKeyModifier {
            get {
                return ((int)(this["HotKeyModifier"]));
            }
            set {
                this["HotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartDelayMS {
            get {
                return ((int)(this["StartDelayMS"]));
            }
            set {
                this["StartDelayMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ConfirmOver {
            get {
                return ((int)(this["ConfirmOver"]));
            }
            set {
                this["ConfirmOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Confirm {
            get {
                return ((bool)(this["Confirm"]));
            }
            set {
                this["Confirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GifLockRatio {
            get {
                return ((bool)(this["GifLockRatio"]));
            }
            set {
                this["GifLockRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16:9")]
        public string GifRatioPreset {
            get {
                return ((string)(this["GifRatioPreset"]));
            }
            set {
                this["GifRatioPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GifLockPixel {
            get {
                return ((bool)(this["GifLockPixel"]));
            }
            set {
                this["GifLockPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int GifPixelWidth {
            get {
                return ((int)(this["GifPixelWidth"]));
            }
            set {
                this["GifPixelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int GifPixelHeight {
            get {
                return ((int)(this["GifPixelHeight"]));
            }
            set {
                this["GifPixelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GifOutput {
            get {
                return ((int)(this["GifOutput"]));
            }
            set {
                this["GifOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GifFolder {
            get {
                return ((string)(this["GifFolder"]));
            }
            set {
                this["GifFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string VideoHotKey {
            get {
                return ((string)(this["VideoHotKey"]));
            }
            set {
                this["VideoHotKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int VideoHotKeyModifier {
            get {
                return ((int)(this["VideoHotKeyModifier"]));
            }
            set {
                this["VideoHotKeyModifier"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int VideoFps {
            get {
                return ((int)(this["VideoFps"]));
            }
            set {
                this["VideoFps"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int VideoSeconds {
            get {
                return ((int)(this["VideoSeconds"]));
            }
            set {
                this["VideoSeconds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VideoQuality {
            get {
                return ((int)(this["VideoQuality"]));
            }
            set {
                this["VideoQuality"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VideoAudioSource {
            get {
                return ((int)(this["VideoAudioSource"]));
            }
            set {
                this["VideoAudioSource"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoLockCursorSize {
            get {
                return ((bool)(this["VideoLockCursorSize"]));
            }
            set {
                this["VideoLockCursorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoClickGlow {
            get {
                return ((bool)(this["VideoClickGlow"]));
            }
            set {
                this["VideoClickGlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoActionLog {
            get {
                return ((bool)(this["VideoActionLog"]));
            }
            set {
                this["VideoActionLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoLockRatio {
            get {
                return ((bool)(this["VideoLockRatio"]));
            }
            set {
                this["VideoLockRatio"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16:9")]
        public string VideoRatioPreset {
            get {
                return ((string)(this["VideoRatioPreset"]));
            }
            set {
                this["VideoRatioPreset"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoLockPixel {
            get {
                return ((bool)(this["VideoLockPixel"]));
            }
            set {
                this["VideoLockPixel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int VideoPixelWidth {
            get {
                return ((int)(this["VideoPixelWidth"]));
            }
            set {
                this["VideoPixelWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int VideoPixelHeight {
            get {
                return ((int)(this["VideoPixelHeight"]));
            }
            set {
                this["VideoPixelHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoOutput {
            get {
                return ((int)(this["VideoOutput"]));
            }
            set {
                this["VideoOutput"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoFolder {
            get {
                return ((string)(this["VideoFolder"]));
            }
            set {
                this["VideoFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string GifHotKey {
            get {
                return ((string)(this["GifHotKey"]));
            }
            set {
                this["GifHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int GifHotKeyModifier {
            get {
                return ((int)(this["GifHotKeyModifier"]));
            }
            set {
                this["GifHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GifFps {
            get {
                return ((int)(this["GifFps"]));
            }
            set {
                this["GifFps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GifSeconds {
            get {
                return ((int)(this["GifSeconds"]));
            }
            set {
                this["GifSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string CaptureHotKey {
            get {
                return ((string)(this["CaptureHotKey"]));
            }
            set {
                this["CaptureHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CaptureHotKeyModifier {
            get {
                return ((int)(this["CaptureHotKeyModifier"]));
            }
            set {
                this["CaptureHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CaptureDelay {
            get {
                return ((int)(this["CaptureDelay"]));
            }
            set {
                this["CaptureDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CaptureOutput {
            get {
                return ((int)(this["CaptureOutput"]));
            }
            set {
                this["CaptureOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CaptureFolder {
            get {
                return ((string)(this["CaptureFolder"]));
            }
            set {
                this["CaptureFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockRatio {
            get {
                return ((bool)(this["LockRatio"]));
            }
            set {
                this["LockRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16:9")]
        public string RatioPreset {
            get {
                return ((string)(this["RatioPreset"]));
            }
            set {
                this["RatioPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockPixel {
            get {
                return ((bool)(this["LockPixel"]));
            }
            set {
                this["LockPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920")]
        public int PixelWidth {
            get {
                return ((int)(this["PixelWidth"]));
            }
            set {
                this["PixelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public int PixelHeight {
            get {
                return ((int)(this["PixelHeight"]));
            }
            set {
                this["PixelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O")]
        public string OcrHotKey {
            get {
                return ((string)(this["OcrHotKey"]));
            }
            set {
                this["OcrHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int OcrHotKeyModifier {
            get {
                return ((int)(this["OcrHotKeyModifier"]));
            }
            set {
                this["OcrHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OcrLanguage {
            get {
                return ((string)(this["OcrLanguage"]));
            }
            set {
                this["OcrLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OcrOutput {
            get {
                return ((int)(this["OcrOutput"]));
            }
            set {
                this["OcrOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OcrKeepLines {
            get {
                return ((bool)(this["OcrKeepLines"]));
            }
            set {
                this["OcrKeepLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HotKeyMode {
            get {
                return ((int)(this["HotKeyMode"]));
            }
            set {
                this["HotKeyMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotKeyTakeOver {
            get {
                return ((string)(this["HotKeyTakeOver"]));
            }
            set {
                this["HotKeyTakeOver"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OcrHotKeyTakeOver {
            get {
                return ((string)(this["OcrHotKeyTakeOver"]));
            }
            set {
                this["OcrHotKeyTakeOver"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CaptureHotKeyTakeOver {
            get {
                return ((string)(this["CaptureHotKeyTakeOver"]));
            }
            set {
                this["CaptureHotKeyTakeOver"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GifHotKeyTakeOver {
            get {
                return ((string)(this["GifHotKeyTakeOver"]));
            }
            set {
                this["GifHotKeyTakeOver"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoHotKeyTakeOver {
            get {
                return ((string)(this["VideoHotKeyTakeOver"]));
            }
            set {
                this["VideoHotKeyTakeOver"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string TextPickHotKey {
            get {
                return ((string)(this["TextPickHotKey"]));
            }
            set {
                this["TextPickHotKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TextPickHotKeyModifier {
            get {
                return ((int)(this["TextPickHotKeyModifier"]));
            }
            set {
                this["TextPickHotKeyModifier"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextPickHotKeyTakeOver {
            get {
                return ((string)(this["TextPickHotKeyTakeOver"]));
            }
            set {
                this["TextPickHotKeyTakeOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string ColorPickHotKey {
            get {
                return ((string)(this["ColorPickHotKey"]));
            }
            set {
                this["ColorPickHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ColorPickHotKeyModifier {
            get {
                return ((int)(this["ColorPickHotKeyModifier"]));
            }
            set {
                this["ColorPickHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorPickHotKeyTakeOver {
            get {
                return ((string)(this["ColorPickHotKeyTakeOver"]));
            }
            set {
                this["ColorPickHotKeyTakeOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorHistory {
            get {
                return ((string)(this["ColorHistory"]));
            }
            set {
                this["ColorHistory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string NoteHotKey {
            get {
                return ((string)(this["NoteHotKey"]));
            }
            set {
                this["NoteHotKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int NoteHotKeyModifier {
            get {
                return ((int)(this["NoteHotKeyModifier"]));
            }
            set {
                this["NoteHotKeyModifier"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteHotKeyTakeOver {
            get {
                return ((string)(this["NoteHotKeyTakeOver"]));
            }
            set {
                this["NoteHotKeyTakeOver"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-MM-dd")]
        public string NoteDateFormat {
            get {
                return ((string)(this["NoteDateFormat"]));
            }
            set {
                this["NoteDateFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dddd, dd MMMM yyyy")]
        public string NoteLongDateFormat {
            get {
                return ((string)(this["NoteLongDateFormat"]));
            }
            set {
                this["NoteLongDateFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-MM-dd HH:mm:ss")]
        public string NoteTimestampFormat {
            get {
                return ((string)(this["NoteTimestampFormat"]));
            }
            set {
                this["NoteTimestampFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NoteAiProvider {
            get {
                return ((int)(this["NoteAiProvider"]));
            }
            set {
                this["NoteAiProvider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteAiModel {
            get {
                return ((string)(this["NoteAiModel"]));
            }
            set {
                this["NoteAiModel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteAiApiKey {
            get {
                return ((string)(this["NoteAiApiKey"]));
            }
            set {
                this["NoteAiApiKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int NoteFontSize {
            get {
                return ((int)(this["NoteFontSize"]));
            }
            set {
                this["NoteFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NoteMonoFont {
            get {
                return ((bool)(this["NoteMonoFont"]));
            }
            set {
                this["NoteMonoFont"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteBanglaToken {
            get {
                return ((string)(this["NoteBanglaToken"]));
            }
            set {
                this["NoteBanglaToken"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteAiBaseUrl {
            get {
                return ((string)(this["NoteAiBaseUrl"]));
            }
            set {
                this["NoteAiBaseUrl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NoteHideTaskbar {
            get {
                return ((bool)(this["NoteHideTaskbar"]));
            }
            set {
                this["NoteHideTaskbar"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteListBounds {
            get {
                return ((string)(this["NoteListBounds"]));
            }
            set {
                this["NoteListBounds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public int NoteDefaultColour {
            get {
                return ((int)(this["NoteDefaultColour"]));
            }
            set {
                this["NoteDefaultColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteSyncProject {
            get {
                return ((string)(this["NoteSyncProject"]));
            }
            set {
                this["NoteSyncProject"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteSyncApiKey {
            get {
                return ((string)(this["NoteSyncApiKey"]));
            }
            set {
                this["NoteSyncApiKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteSyncSecret {
            get {
                return ((string)(this["NoteSyncSecret"]));
            }
            set {
                this["NoteSyncSecret"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteSyncEmail {
            get {
                return ((string)(this["NoteSyncEmail"]));
            }
            set {
                this["NoteSyncEmail"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteSyncUid {
            get {
                return ((string)(this["NoteSyncUid"]));
            }
            set {
                this["NoteSyncUid"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteSyncToken {
            get {
                return ((string)(this["NoteSyncToken"]));
            }
            set {
                this["NoteSyncToken"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoteSyncOn {
            get {
                return ((bool)(this["NoteSyncOn"]));
            }
            set {
                this["NoteSyncOn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteSyncStamp {
            get {
                return ((string)(this["NoteSyncStamp"]));
            }
            set {
                this["NoteSyncStamp"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpgraded {
            get {
                return ((bool)(this["SettingsUpgraded"]));
            }
            set {
                this["SettingsUpgraded"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string ImageEditorHotKey {
            get {
                return ((string)(this["ImageEditorHotKey"]));
            }
            set {
                this["ImageEditorHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ImageEditorHotKeyModifier {
            get {
                return ((int)(this["ImageEditorHotKeyModifier"]));
            }
            set {
                this["ImageEditorHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public int EditorRightPanelWidth {
            get {
                return ((int)(this["EditorRightPanelWidth"]));
            }
            set {
                this["EditorRightPanelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditorWindowWidth {
            get {
                return ((int)(this["EditorWindowWidth"]));
            }
            set {
                this["EditorWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditorWindowHeight {
            get {
                return ((int)(this["EditorWindowHeight"]));
            }
            set {
                this["EditorWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorWindowMaximized {
            get {
                return ((bool)(this["EditorWindowMaximized"]));
            }
            set {
                this["EditorWindowMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string EditorRulerUnit {
            get {
                return ((string)(this["EditorRulerUnit"]));
            }
            set {
                this["EditorRulerUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorSnapToUnit {
            get {
                return ((bool)(this["EditorSnapToUnit"]));
            }
            set {
                this["EditorSnapToUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageEditorHotKeyTakeOver {
            get {
                return ((string)(this["ImageEditorHotKeyTakeOver"]));
            }
            set {
                this["ImageEditorHotKeyTakeOver"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string DateHotKey {
            get {
                return ((string)(this["DateHotKey"]));
            }
            set {
                this["DateHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int DateHotKeyModifier {
            get {
                return ((int)(this["DateHotKeyModifier"]));
            }
            set {
                this["DateHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DateHotKeyTakeOver {
            get {
                return ((string)(this["DateHotKeyTakeOver"]));
            }
            set {
                this["DateHotKeyTakeOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string LongDateHotKey {
            get {
                return ((string)(this["LongDateHotKey"]));
            }
            set {
                this["LongDateHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int LongDateHotKeyModifier {
            get {
                return ((int)(this["LongDateHotKeyModifier"]));
            }
            set {
                this["LongDateHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LongDateHotKeyTakeOver {
            get {
                return ((string)(this["LongDateHotKeyTakeOver"]));
            }
            set {
                this["LongDateHotKeyTakeOver"] = value;
            }
        }
    
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public string AotHotKey {
            get {
                return ((string)(this["AotHotKey"]));
            }
            set {
                this["AotHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AotHotKeyModifier {
            get {
                return ((int)(this["AotHotKeyModifier"]));
            }
            set {
                this["AotHotKeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AotHotKeyTakeOver {
            get {
                return ((string)(this["AotHotKeyTakeOver"]));
            }
            set {
                this["AotHotKeyTakeOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AotOpacity {
            get {
                return ((int)(this["AotOpacity"]));
            }
            set {
                this["AotOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AotClickUnpins {
            get {
                return ((bool)(this["AotClickUnpins"]));
            }
            set {
                this["AotClickUnpins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AotTitleMark {
            get {
                return ((bool)(this["AotTitleMark"]));
            }
            set {
                this["AotTitleMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AotNotify {
            get {
                return ((bool)(this["AotNotify"]));
            }
            set {
                this["AotNotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AotSound {
            get {
                return ((bool)(this["AotSound"]));
            }
            set {
                this["AotSound"] = value;
            }
        }
}
}
